source 'https://rubygems.org'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

gem 'json', '~> 1.8.1'


gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'jbuilder', '~> 2.0'
gem 'websocket-rails', '~> 0.7.0'
gem 'mysql2', '~> 0.3.16'

gem 'byebug', group: [:development, :test]

